ghdl : 
	ghdl -a --work=work_lib ../../parameters/parameters.vhd
	ghdl -a --work=work_lib ../../generic_layer/src/generic_layer.vhd
	ghdl -a --work=work_lib generic_fc_nn.vhd

clean : 
	rm -f *.cf *.o
